/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    person: Person;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    person: PersonSelect<false> | PersonSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * Unique identifier — used for preview subdomain (slug.adriandelrosario.live)
   */
  slug: string;
  /**
   * Custom domain (e.g. janesmith.com) — leave blank until provisioned
   */
  domain?: string | null;
  theme?: ('minimal' | 'editorial' | 'bold' | 'custom') | null;
  professionPack?: ('seo-specialist' | 'physician' | 'attorney' | 'athlete' | 'executive') | null;
  status?: ('active' | 'inactive') | null;
  /**
   * CSS injected after theme styles — tokens preferred
   */
  customCss?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Schema.org/Person record — one per tenant
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "person".
 */
export interface Person {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * schema:name — full legal or professional name
   */
  name: string;
  /**
   * schema:jobTitle — primary professional title
   */
  jobTitle?: string | null;
  /**
   * Short positioning statement for hero section (not Schema.org native)
   */
  tagline?: string | null;
  /**
   * schema:description — professional bio (plain text, used in JSON-LD and meta)
   */
  description?: string | null;
  /**
   * schema:image — primary profile photo
   */
  image?: (number | null) | Media;
  /**
   * schema:url — canonical personal website URL
   */
  url?: string | null;
  /**
   * schema:email — public contact email
   */
  email?: string | null;
  /**
   * schema:telephone — public contact number
   */
  telephone?: string | null;
  /**
   * schema:sameAs — social profile URLs (LinkedIn, Twitter/X, GitHub…)
   */
  sameAs?:
    | {
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * schema:worksFor — current primary employer/organisation
   */
  worksFor?: {
    name?: string | null;
    url?: string | null;
  };
  /**
   * schema:hasOccupation — occupation history / current roles
   */
  hasOccupation?:
    | {
        name: string;
        organization?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * schema:alumniOf — educational institutions attended
   */
  alumniOf?:
    | {
        name: string;
        degree?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * schema:hasCredential — certifications, licences, professional credentials
   */
  hasCredential?:
    | {
        name: string;
        issuedBy?: string | null;
        dateIssued?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * schema:award — awards and recognitions
   */
  award?:
    | {
        name: string;
        issuedBy?: string | null;
        date?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * schema:knowsAbout — topics, skills, and subject-matter expertise
   */
  knowsAbout?:
    | {
        topic: string;
        level?: ('expert' | 'advanced' | 'intermediate') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * schema:aggregateRating — summary rating (e.g. from Google/Yelp)
   */
  aggregateRating?: {
    ratingValue?: number | null;
    reviewCount?: number | null;
    bestRating?: number | null;
  };
  /**
   * schema:review — individual reviews / testimonials
   */
  review?:
    | {
        author: string;
        reviewBody?: string | null;
        ratingValue?: number | null;
        datePublished?: string | null;
        isTestimonial?: boolean | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Alt text for accessibility and SEO
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'person';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  slug?: T;
  domain?: T;
  theme?: T;
  professionPack?: T;
  status?: T;
  customCss?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "person_select".
 */
export interface PersonSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  jobTitle?: T;
  tagline?: T;
  description?: T;
  image?: T;
  url?: T;
  email?: T;
  telephone?: T;
  sameAs?:
    | T
    | {
        url?: T;
        label?: T;
        id?: T;
      };
  worksFor?:
    | T
    | {
        name?: T;
        url?: T;
      };
  hasOccupation?:
    | T
    | {
        name?: T;
        organization?: T;
        startDate?: T;
        endDate?: T;
        description?: T;
        id?: T;
      };
  alumniOf?:
    | T
    | {
        name?: T;
        degree?: T;
        startDate?: T;
        endDate?: T;
        url?: T;
        id?: T;
      };
  hasCredential?:
    | T
    | {
        name?: T;
        issuedBy?: T;
        dateIssued?: T;
        url?: T;
        id?: T;
      };
  award?:
    | T
    | {
        name?: T;
        issuedBy?: T;
        date?: T;
        url?: T;
        id?: T;
      };
  knowsAbout?:
    | T
    | {
        topic?: T;
        level?: T;
        id?: T;
      };
  aggregateRating?:
    | T
    | {
        ratingValue?: T;
        reviewCount?: T;
        bestRating?: T;
      };
  review?:
    | T
    | {
        author?: T;
        reviewBody?: T;
        ratingValue?: T;
        datePublished?: T;
        isTestimonial?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}